package Support;

// represents activity types (e.g. lectures, labs, tutorials)
public enum Activity {
    LECTURE,
    LABORATORY,
    TUTORIAL,
    WAITLIST,
    SEMINAR,
    DISCUSSION,
    DIRECTED_STUDY,
    THESIS,
    PRACTICUM,
    WORK_PLACEMENT,
    LECTURE_LAB,
    STUDIO,
    EXCHANGE_PROGRAM,
    WEB_ORIENTATED,
    PROJECT,
    REHERESAL,
    WORKSHOP,
    ESSAY_REPORT,
    PROBLEM_SECSSION,
    LECTURE_SEMINAR,
    LECTURE_DISCUSSION,
    RESEARCH,
    LAB_SEMINAR,
    FLEXIBLE_LEARNING,
    FIELD_TRIP,
    OPTIONAL,
    RESERVED
}
